use_frameworks!

platform :ios, '10.0'

target 'BCore_Example' do
  pod 'BCore', :path => '../'

  target 'BCore_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 8.0.7'
  end
end
